export default [
  {
    id: "KYR5",
    name: "Κιουρδί",
    type: "Minor",
    variantNames: ["Μινόρε"],
    intervals: [2, 1, 2, 2],
  },
  {
    id: "KYR4",
    name: "Κιουρδί",
    type: "Minor",
    variantNames: ["Μινόρε"],
    intervals: [2, 1, 2],
  },
  {
    id: "USK5",
    name: "Ουσάκ",
    type: "Minor",
    intervals: [1, 2, 2, 2],
  },
  {
    id: "USK4",
    name: "Ουσάκ",
    type: "Minor",
    intervals: [1, 2, 2],
  },
  {
    id: "SBH5",
    name: "Σαμπάχ",
    type: "Minor",
    intervals: [2, 1, 1, 3],
  },
  {
    id: "NKR5",
    name: "Νικρίζ",
    type: "Minor",
    variantNames: ["Νιαβέντ"],
    intervals: [2, 1, 3, 1],
  },
  {
    id: "RST5",
    name: "Ραστ",
    type: "Major",
    variantNames: ["Ματζόρε"],
    intervals: [2, 2, 1, 2],
  },
  {
    id: "RST4",
    name: "Ραστ",
    type: "Major",
    variantNames: ["Ματζόρε"],
    intervals: [2, 2, 1],
  },
  {
    id: "HZM5",
    name: "Χουζάμ",
    type: "Major",
    variantNames: ["Σεγκιάχ"],
    intervals: [3, 1, 1, 2],
  },
  {
    id: "HZM4",
    name: "Χουζάμ",
    type: "Major",
    variantNames: ["Σεγκιάχ"],
    intervals: [3, 1, 1],
  },
  {
    id: "HTZ5",
    name: "Χιτζάζ",
    type: "Major",
    intervals: [1, 3, 1, 2],
  },
  {
    id: "HTZ4",
    name: "Χιτζάζ",
    type: "Major",
    intervals: [1, 3, 1],
  },
  {
    id: "HTZN5",
    name: "Χιτζάζ Νικρίζ",
    type: "Major",
    variantNames: ["Χιτζάζ Νιαβέντ"],
    intervals: [1, 3, 2, 1],
  },
];
