export default [
  { name: "Χαρικλάκι", makamIds: ["RAST"], authors: ["Παναγιώτης Τούντας"] },
  { name: "Ζεμπεκάνο Σπανιόλο", makamIds: ["RAST"], authors: ["Γιώργος Μπάτης"] },
  { name: "Μαρίκα χασικλού", makamIds: ["RAST"], authors: ["Βαγγέλης Παπάζογλου"] },
  { name: "Γκαμηλιέρικο", makamIds: ["RAST"], authors: ["Γιώργος Μπάτης"] },
  {
    name: "Αλεξανδριανή φελάχα",
    makamIds: ["RAST"],
    authors: ["Ρόζα Εσκενάζυ", "Δημήτρης Σέμσης"],
  },
  { name: "Η Μαρία η δασκάλα", makamIds: ["RAST"], authors: ["Παναγιώτης Τούντας"] },
  { name: "Οι τρεις ορφανές", makamIds: ["RAST"], authors: ["Γρηγόρης Ασίκης"] },
  {
    name: "Μες του Βαβούλα τη γούβα",
    makamIds: ["RAST"],
    authors: ["Στράτος Παγιουμτζής", "Στέλιος Κερομύτης"],
  },
  { name: "Στη Δραπετσώνα", makamIds: ["RAST", "NEVESER"], authors: ["Παναγιώτης Τούντας"] },
  { name: "Γιαννάκης", makamIds: ["RAST", "NEVESER"], authors: ["Κώστας Σκαρβέλης"] },
  { name: "Ώρες με θρέφει ο λουλάς", makamIds: ["RAST_SAZKAR"], authors: ["Μάρκος Βαμβακάρης"] },
  { name: "Στο Φάληρο που πλένεσαι", makamIds: ["RAST_SAZKAR"], authors: ["Μάρκος Βαμβακάρης"] },
  { name: "Καραβοτσακίσματα", makamIds: ["RAST_SAZKAR", "HUZAM"], authors: ["Μάρκος Βαμβακάρης"] },
  { name: "Κατιφές", makamIds: ["USAK"], authors: ["Ανώνυμος"] },
  { name: "Βυρωνιώτισσα", makamIds: ["USAK"], authors: ["Γρηγόρης Ασίκης"] },
  { name: "Γυφτοπούλα στο χαμάμ", makamIds: ["USAK"], authors: ["Γιώργος Μπάτης"] },
  { name: "Αρμενίτσα", makamIds: ["USAK"], authors: ["Κώστας Καρίπης"] },
  { name: "Ο Μυλωνάς", makamIds: ["USAK"], authors: ["Δημήτρης Σέμσης", "Σταύρος Παντελίδης"] },
  {
    name: "Έτσι Μαρίκα δέχομαι",
    makamIds: ["USAK"],
    authors: ["Γώργος Πετροπουλέας", "Δημήτρης Σέμσης"],
  },
  { name: "Ο Πίκινος", makamIds: ["USAK"], authors: ["Κώστας Ρούκουνας"] },
  {
    name: "Μην ορκίζεσαι βρε ψεύτρα",
    makamIds: ["USAK"],
    authors: ["Γιώργος Πετροπουλέας", "Δημήτρης Σέμσης"],
  },
  { name: "Καθρέφτης θέλω να ΄μουνα", makamIds: ["USAK"], authors: ["Κώστας Ρούκουνας"] },
  {
    name: "Μεθυσμένος (Νεβά τσιφτετέλι)",
    makamIds: ["USAK", "SABAH"],
    authors: ["Γιάννης Δράγατσης"],
  },
  {
    name: "Σ' έναν τεκέ σκαρώσανε",
    makamIds: ["USAK", "SABAH"],
    authors: ["Δημήτρης Περδικόπουλος", "Βασίλης Τσιτσάνης"],
  },
];
