export default [
  { name: "Χαρικλάκι", makamIds: ["RAST"], authors: ["Παναγιώτης Τούντας"], year: 1933 },
  { name: "Ζεμπεκάνο Σπανιόλο", makamIds: ["RAST"], authors: ["Γιώργος Μπάτης"], year: 1934 },
  { name: "Μαρίκα χασικλού", makamIds: ["RAST"], authors: ["Βαγγέλης Παπάζογλου"], year: 1934 },
  { name: "Γκαμηλιέρικο", makamIds: ["RAST"], authors: ["Γιώργος Μπάτης"], year: 1934 },
  {
    name: "Αλεξανδριανή φελάχα",
    makamIds: ["RAST"],
    authors: ["Ρόζα Εσκενάζυ|Δημήτρης Σέμσης"],
    year: 1934,
  },
  { name: "Η Μαρίκα η δασκάλα", makamIds: ["RAST"], authors: ["Παναγιώτης Τούντας"], year: 1936 },
  { name: "Οι τρεις ορφανές", makamIds: ["RAST"], authors: ["Γρηγόρης Ασίκης"], year: 1937 },
  {
    name: "Μες του Βαβούλα τη γούβα",
    makamIds: ["RAST"],
    authors: ["Στράτος Παγιουμτζής|Στέλιος Κερομύτης"],
    year: 1937,
  },
  {
    name: "Στη Δραπετσώνα",
    makamIds: ["RAST|NEVESER"],
    authors: ["Παναγιώτης Τούντας"],
    year: 1934,
  },
  { name: "Γιαννάκης", makamIds: ["RAST|NEVESER"], authors: ["Κώστας Σκαρβέλης"], year: 1936 },
  {
    name: "Ώρες με θρέφει ο λουλάς",
    makamIds: ["RAST_SAZKAR"],
    authors: ["Μάρκος Βαμβακάρης"],
    year: 1933,
  },
  {
    name: "Στο Φάληρο που πλένεσαι",
    makamIds: ["RAST_SAZKAR"],
    authors: ["Μάρκος Βαμβακάρης"],
    year: 1937,
  },
  {
    name: "Καραβοτσακίσματα",
    makamIds: ["RAST_SAZKAR|HUZAM"],
    authors: ["Μάρκος Βαμβακάρης"],
    year: 1936,
  },
  { name: "Κατιφές", makamIds: ["USSAK"], authors: [""], year: 1931 },
  { name: "Βυρωνιώτισσα", makamIds: ["USSAK"], authors: ["Γρηγόρης Ασίκης"], year: 1935 },
  { name: "Γυφτοπούλα στο χαμάμ", makamIds: ["USSAK"], authors: ["Γιώργος Μπάτης"], year: 1934 },
  { name: "Αρμενίτσα", makamIds: ["USSAK"], authors: ["Κώστας Καρίπης"], year: 1934 },
  {
    name: "Ο μυλωνάς",
    makamIds: ["USSAK"],
    authors: ["Δημήτρης Σέμσης|Σταύρος Παντελίδης"],
    year: 1934,
  },
  {
    name: "Έτσι Μαρίκα δέχομαι",
    makamIds: ["USSAK"],
    authors: ["Γώργος Πετροπουλέας|Δημήτρης Σέμσης"],
    year: 1935,
  },
  { name: "Ο Πίκινος", makamIds: ["USSAK"], authors: ["Κώστας Ρούκουνας"], year: 1934 },
  {
    name: "Μην ορκίζεσαι βρε ψεύτρα",
    makamIds: ["USSAK"],
    authors: ["Γιώργος Πετροπουλέας|Δημήτρης Σέμσης"],
    year: 1936,
  },
  {
    name: "Καθρέφτης θέλω να ΄μουνα",
    makamIds: ["USSAK"],
    authors: ["Κώστας Ρούκουνας"],
    year: 1936,
  },
  {
    name: "Μεθυσμένος (Νεβά τσιφτετέλι)",
    makamIds: ["USSAK|SABAH"],
    authors: ["Γιάννης Δράγατσης"],
    year: 1932,
  },
  {
    name: "Σ' έναν τεκέ σκαρώσανε",
    makamIds: ["USSAK|SABAH"],
    authors: ["Δημήτρης Περδικόπουλος|Βασίλης Τσιτσάνης"],
    year: 1936,
  },
  { name: "Ο ψύλλος", makamIds: ["SEGAH"], authors: ["Σταύρος Παντελίδης"], year: 1932 },
  { name: "Ο Νικοκλάκιας", makamIds: ["SEGAH"], authors: ["Βαγγέλης Παπάζογλου"], year: 1934 },
  { name: "Οι λαχανάδες", makamIds: ["SEGAH"], authors: ["Βαγγέλης Παπάζογλου"], year: 1934 },
  {
    name: "Σαν εγύριζα απ' την Πύλο",
    makamIds: ["SEGAH"],
    authors: ["Βαγγέλης Παπάζογλου"],
    year: 1935,
  },
  { name: "Ο φασούλας", makamIds: ["SEGAH"], authors: ["Γιώργος Μπάτης"], year: 1936 },
  {
    name: "Γεντί Κουλέ",
    makamIds: ["SEGAH"],
    authors: ["Αιμίλιος Σαββίδης|Σώσος Ιωαννίδης"],
    year: 1934,
  },
  {
    name: "Βάλε με στην αγκαλιά σου",
    makamIds: ["HUSEYINI"],
    authors: ["Στελλάκης Περπινιάδης"],
    year: 1934,
  },
  {
    name: "Μα τι να κάνω σ' αγαπώ",
    makamIds: ["HUSEYINI"],
    authors: ["Γιώργος Κάβουρας"],
    year: 1939,
  },
  { name: "Ο τζογαδόρος", makamIds: ["HUSEYINI"], authors: ["Αντώνης Διαμαντίδης"], year: 1933 },
  { name: "Πάμε για το πράσο", makamIds: ["HUSEYINI"], authors: ["Ρίτα Αμπατζή"], year: 1934 },
  { name: "Πατρινιά", makamIds: ["HUSEYINI"], authors: ["Ρόζα Εσκενάζυ"], year: 1935 },
  {
    name: "Τα δυο σου χέρια πήρανε",
    makamIds: ["HUSEYINI"],
    authors: ["Μάρκος Βαμβακάρης"],
    year: 1939,
  },
  {
    name: "Το παιχνίδι του Αμερικάνου",
    makamIds: ["HUSEYINI"],
    authors: ["Ρίτα Αμπατζή"],
    year: 1936,
  },
  { name: "Το φλυτζάνι του Γιάννη", makamIds: ["HUSEYINI"], authors: ["Ρίτα Αμπατζή"], year: 1934 },
  {
    name: "Τούτ' οι μπάτσοι που 'ρθαν τώρα",
    makamIds: ["HUSEYINI"],
    authors: ["Γιάννης Ιωαννίδης"],
    year: 1929,
  },
  {
    name: "Γεια σου Λόλα μερακλού",
    makamIds: ["HUSEYINI|KARCIGAR"],
    authors: ["Κώστας Ρούκουνας"],
    year: 1934,
  },
  {
    name: "Οι γυρολόγοι",
    makamIds: ["HUSEYINI|KARCIGAR"],
    authors: ["Κώστας Ρούκουνας"],
    year: 1935,
  },
  {
    name: "Τουρκολιμανιώτισσα",
    makamIds: ["HUSEYINI|KARCIGAR"],
    authors: ["Γρηγόρης Ασίκης"],
    year: 1932,
  },
  { name: "Τσερκές", makamIds: ["HUSEYINI|KARCIGAR"], authors: ["Ρίτα Αμπατζή"], year: 1933 },
  {
    name: "Βλάμισσα",
    makamIds: ["HUSEYINI|HUZAM"],
    authors: ["Στελλάκης Περπινιάδης"],
    year: 1936,
  },
  {
    name: "Βρε μάγκες δυο στη φυλακή",
    makamIds: ["HUSEYINI|HUZAM"],
    authors: ["Ρίτα Αμπατζή"],
    year: 1934,
  },
  { name: "Αληθινή αγαπή", makamIds: ["SABAH"], authors: ["Ρόζα Εσκενάζυ"], year: 1936 },
  { name: "Γιαλό - γιαλό", makamIds: ["SABAH"], authors: ["Κώστας Τσανάκος"], year: 1937 },
  { name: "Ήσουνα ξυπόλητη", makamIds: ["SABAH"], authors: ["Α. Κωστής"], year: 1930 },
  { name: "Ο ξενιτεμένος", makamIds: ["SABAH"], authors: ["Ρόζα Εσκενάζυ"], year: 1935 },
  { name: "Ο παπατζής", makamIds: ["SABAH"], authors: ["Στελλάκης Περπινιάδης"], year: 1934 },
  { name: "Ο συνάχης", makamIds: ["SABAH"], authors: ["Μάρκος Βαμβακάρης"], year: 1934 },
  { name: "Οι φυλακές του Ωρωπού", makamIds: ["SABAH"], authors: ["Γιώργος Μπάτης"], year: 1934 },
  { name: "Σορόπης", makamIds: ["SABAH"], authors: ["Κώστας Ρούκουνας"], year: 1935 },
  { name: "Στην υπόγα", makamIds: ["SABAH"], authors: ["Α. Κωστής"], year: 1930 },
  { name: "Τσερκέζα", makamIds: ["SABAH"], authors: ["Ρόζα Εσκενάζυ"], year: 1934 },
  { name: "Ψεύτρα", makamIds: ["SABAH|NIKRIZ"], authors: ["Ευάγγελος Σωφρονίου"], year: 1930 },
  { name: "Γελασμένος", makamIds: ["HUZAM"], authors: ["Στελλάκης Περπινιάδης"], year: 1939 },
  { name: "Για την αγάπη μου", makamIds: ["HUZAM"], authors: ["Ρίτα Αμπατζή"], year: 1934 },
  { name: "Η μπαμπέσα", makamIds: ["HUZAM"], authors: ["Ρόζα Εσκενάζυ"], year: 1934 },
  { name: "Ντερβίσαινα", makamIds: ["HUZAM"], authors: ["Κώστας Ρούκουνας"], year: 1934 },
  {
    name: "Σαν είσαι μάγκας και νταής",
    makamIds: ["HUZAM"],
    authors: ["Μάρκος Βαμβακάρης|Ρίτα Αμπατζή"],
    year: 1934,
  },
  { name: "Στρι ρε κουτσαβάκι", makamIds: ["HUZAM"], authors: ["Χρήστος Τσαγκαράκης"], year: 1935 },
  {
    name: "Αχ βρε θάλασσα κακούργα",
    makamIds: ["HIJAZ"],
    authors: ["Μαριώ Μαρκοπούλου"],
    year: 1935,
  },
  { name: "Γίνομαι άντρας", makamIds: ["HIJAZ"], authors: ["Ρόζα Εσκενάζυ"], year: 1933 },
  { name: "Δεν σ' αγαπώ δεν σ' αγαπώ", makamIds: ["HIJAZ"], authors: ["Ρίτα Αμπατζή"], year: 1937 },
  {
    name: "Η Μαρίτσα η Σμυρνιά",
    makamIds: ["HIJAZ"],
    authors: ["Αντώνης Διαμαντίδης"],
    year: 1929,
  },
  { name: "Η Παγκρατιώτισσα", makamIds: ["HIJAZ"], authors: ["Ευάγγελος Σωφρονίου"], year: 1929 },
  { name: "Η Πολίτισσα", makamIds: ["HIJAZ"], authors: ["Ευάγγελος Σωφρονίου"], year: 1929 },
  { name: "Η πουλημένη στην ξενιτιά", makamIds: ["HIJAZ"], authors: ["Ρόζα Εσκενάζυ"], year: 1935 },
  {
    name: "Η φωνή του αργιλέ",
    makamIds: ["HIJAZ"],
    authors: ["Στελλάκης Περπινιάδης"],
    year: 1934,
  },
  { name: "Θέλω απόψε να γλεντήσω", makamIds: ["HIJAZ"], authors: ["Ρόζα Εσκενάζυ"], year: 1934 },
  {
    name: "Κουτσαβάκι (βρε μάγκα το μαχαίρι σου)",
    makamIds: ["HIJAZ"],
    authors: ["Ανέστης Δελιάς"],
    year: 1936,
  },
  { name: "Μανώλης ο χασικλής", makamIds: ["HIJAZ"], authors: ["Γιώργος Βιδάλης"], year: 1929 },
  {
    name: "Μια όμορφη μελαχρινή",
    makamIds: ["HIJAZ"],
    authors: ["Μάρκος Βαμβακάρης|Απόστολος Χατζηχρήστος"],
    year: 1939,
  },
  { name: "Μου είπαν να μην σ' αγαπώ", makamIds: ["HIJAZ"], authors: ["Νότα Καλλέλη"], year: 1939 },
  { name: "Ο αργιλές", makamIds: ["HIJAZ"], authors: ["Στελλάκης Περπινιάδης"], year: 1933 },
  { name: "Ο πρεζάκιας", makamIds: ["HIJAZ"], authors: ["Αντώνης Καλυβόπουλος"], year: 1936 },
  { name: "Πάλι μου κάνεις τον βαρύ", makamIds: ["HIJAZ"], authors: ["Ρόζα Εσκενάζυ"], year: 1936 },
  {
    name: "Στους Ποδαράδες μια Πολίτισσα",
    makamIds: ["HIJAZ"],
    authors: ["Ευάγγελος Σωφρονίου"],
    year: 1930,
  },
  { name: "Της το βγάλανε", makamIds: ["HIJAZ"], authors: ["Ρόζα Εσκενάζυ"], year: 1935 },
  { name: "Το μάγκικο", makamIds: ["HIJAZ"], authors: ["Ρίτα Αμπατζή"], year: 1937 },
  { name: "Το παιδί του δρόμου", makamIds: ["HIJAZ"], authors: ["Γιώργος Κάβουρας"], year: 1937 },
  { name: "Το χασαπάκι", makamIds: ["HIJAZ"], authors: ["Ρόζα Εσκενάζυ"], year: 1931 },
  {
    name: "Φέρτε πρέζα να πρεζάρω",
    makamIds: ["HIJAZ"],
    authors: ["Στελλάκης Περπινιάδης"],
    year: 1934,
  },
  { name: "Κουκλάκι", makamIds: ["HIJAZ|SABAH"], authors: ["Ευάγγελος Σωφρονίου"], year: 1929 },
  { name: "Λιλή η σκανδαλιάρα", makamIds: ["HIJAZ|SABAH"], authors: ["Ρόζα Εσκενάζυ"], year: 1932 },
  {
    name: "Το κουκλί της Κοκκινιάς",
    makamIds: ["HIJAZ|SABAH"],
    authors: ["Ρόζα Εσκενάζυ"],
    year: 1929,
  },
];
