export default [
  { name: "Χαρικλάκι", makamIds: ["RAST"], authors: ["Παναγιώτης Τούντας"], year: 1933 },
  { name: "Ζεμπεκάνο Σπανιόλο", makamIds: ["RAST"], authors: ["Γιώργος Μπάτης"], year: 1934 },
  { name: "Μαρίκα χασικλού", makamIds: ["RAST"], authors: ["Βαγγέλης Παπάζογλου"], year: 1934 },
  { name: "Γκαμηλιέρικο", makamIds: ["RAST"], authors: ["Γιώργος Μπάτης"], year: 1934 },
  {
    name: "Αλεξανδριανή φελάχα",
    makamIds: ["RAST"],
    authors: ["Ρόζα Εσκενάζυ|Δημήτρης Σέμσης"],
    year: 1934,
  },
  { name: "Η Μαρίκα η δασκάλα", makamIds: ["RAST"], authors: ["Παναγιώτης Τούντας"], year: 1936 },
  { name: "Οι τρεις ορφανές", makamIds: ["RAST"], authors: ["Γρηγόρης Ασίκης"], year: 1937 },
  {
    name: "Μες του Βαβούλα τη γούβα",
    makamIds: ["RAST"],
    authors: ["Στράτος Παγιουμτζής|Στέλιος Κερομύτης"],
    year: 1937,
  },
  {
    name: "Στη Δραπετσώνα",
    makamIds: ["RAST|NEVESER"],
    authors: ["Παναγιώτης Τούντας"],
    year: 1934,
  },
  { name: "Γιαννάκης", makamIds: ["RAST|NEVESER"], authors: ["Κώστας Σκαρβέλης"], year: 1936 },
  {
    name: "Ώρες με θρέφει ο λουλάς",
    makamIds: ["RAST_SAZKAR"],
    authors: ["Μάρκος Βαμβακάρης"],
    year: 1933,
  },
  {
    name: "Στο Φάληρο που πλένεσαι",
    makamIds: ["RAST_SAZKAR"],
    authors: ["Μάρκος Βαμβακάρης"],
    year: 1937,
  },
  {
    name: "Καραβοτσακίσματα",
    makamIds: ["RAST_SAZKAR|HUZAM"],
    authors: ["Μάρκος Βαμβακάρης"],
    year: 1936,
  },
  { name: "Κατιφές", makamIds: ["USAK"], authors: ["Ανώνυμος"], year: 1931 },
  { name: "Βυρωνιώτισσα", makamIds: ["USAK"], authors: ["Γρηγόρης Ασίκης"], year: 1935 },
  { name: "Γυφτοπούλα στο χαμάμ", makamIds: ["USAK"], authors: ["Γιώργος Μπάτης"], year: 1934 },
  { name: "Αρμενίτσα", makamIds: ["USAK"], authors: ["Κώστας Καρίπης"], year: 1934 },
  {
    name: "Ο μυλωνάς",
    makamIds: ["USAK"],
    authors: ["Δημήτρης Σέμσης|Σταύρος Παντελίδης"],
    year: 1934,
  },
  {
    name: "Έτσι Μαρίκα δέχομαι",
    makamIds: ["USAK"],
    authors: ["Γώργος Πετροπουλέας|Δημήτρης Σέμσης"],
    year: 1935,
  },
  { name: "Ο Πίκινος", makamIds: ["USAK"], authors: ["Κώστας Ρούκουνας"], year: 1934 },
  {
    name: "Μην ορκίζεσαι βρε ψεύτρα",
    makamIds: ["USAK"],
    authors: ["Γιώργος Πετροπουλέας|Δημήτρης Σέμσης"],
    year: 1936,
  },
  {
    name: "Καθρέφτης θέλω να ΄μουνα",
    makamIds: ["USAK"],
    authors: ["Κώστας Ρούκουνας"],
    year: 1936,
  },
  {
    name: "Μεθυσμένος (Νεβά τσιφτετέλι)",
    makamIds: ["USAK|SABAH"],
    authors: ["Γιάννης Δράγατσης"],
    year: 1932,
  },
  {
    name: "Σ' έναν τεκέ σκαρώσανε",
    makamIds: ["USAK|SABAH"],
    authors: ["Δημήτρης Περδικόπουλος|Βασίλης Τσιτσάνης"],
    year: 1936,
  },
  { name: "Ο ψύλλος", makamIds: ["SEGAH"], authors: ["Σταύρος Παντελίδης"], year: 1932 },
  { name: "Ο Νικοκλάκιας", makamIds: ["SEGAH"], authors: ["Βαγγέλης Παπάζογλου"], year: 1934 },
  { name: "Οι λαχανάδες", makamIds: ["SEGAH"], authors: ["Βαγγέλης Παπάζογλου"], year: 1934 },
  {
    name: "Σαν εγύριζα απ' την Πύλο",
    makamIds: ["SEGAH"],
    authors: ["Βαγγέλης Παπάζογλου"],
    year: 1935,
  },
  { name: "Ο φασούλας", makamIds: ["SEGAH"], authors: ["Γιώργος Μπάτης"], year: 1936 },
  {
    name: "Γεντί Κουλέ",
    makamIds: ["SEGAH"],
    authors: ["Αιμίλιος Σαββίδης|Σώσος Ιωαννίδης"],
    year: 1934,
  },
];
